{
 "title": "Rio Performance",
 "description": "A dashboard for visualizing results from the k6.io load testing tool, using the InfluxDB exporter.Based on https://grafana.com/dashboards/4411",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Environment", "label": "Environment", "query": "dev,test,uat" },
   {
    "name": "Scenarios",
    "label": "Scenarios",
    "query": "SHOW TAG VALUES WITH KEY = \"scenario\""
   },
   {
    "name": "Group",
    "label": "Group",
    "query": "SHOW TAG VALUES WITH KEY = \"group\""
   },
   {
    "name": "URL",
    "label": "URL",
    "query": "SHOW TAG VALUES WITH KEY = \"name\""
   }
  ]
 },
 "panels": [
  {
   "title": "Response Minimum",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "format": "ms",
   "valueName": "min",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http_req_duration",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/^$URL$/" },
      { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$Group$/" },
      { "condition": "AND", "key": "scenario", "operator": "=~", "value": "/^$Scenarios$/" },
      { "condition": "AND", "key": "env", "operator": "=~", "value": "/^$Environment$/" }
     ]
    }
   ]
  },
  {
   "title": "Response Median",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 0 },
   "format": "ms",
   "valueName": "avg",
   "targets": [
    {
     "measurement": "http_req_duration",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/^$URL$/" },
      { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$Group$/" },
      { "condition": "AND", "key": "scenario", "operator": "=~", "value": "/^$Scenarios$/" },
      { "condition": "AND", "key": "env", "operator": "=~", "value": "/^$Environment$/" }
     ]
    }
   ]
  },
  {
   "title": "Response Mean",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 0 },
   "format": "ms",
   "valueName": "avg",
   "targets": [
    {
     "measurement": "http_req_duration",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/^$URL$/" },
      { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$Group$/" },
      { "condition": "AND", "key": "scenario", "operator": "=~", "value": "/^$Scenarios$/" },
      { "condition": "AND", "key": "env", "operator": "=~", "value": "/^$Environment$/" }
     ]
    }
   ]
  },
  {
   "title": "Response p95",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 0 },
   "format": "ms",
   "valueName": "avg",
   "targets": [
    {
     "measurement": "http_req_duration",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [
         95
        ],
        "type": "percentile"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/^$URL$/" },
      { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$Group$/" },
      { "condition": "AND", "key": "scenario", "operator": "=~", "value": "/^$Scenarios$/" },
      { "condition": "AND", "key": "env", "operator": "=~", "value": "/^$Environment$/" }
     ]
    }
   ]
  },
  {
   "title": "Response Maximum",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 0 },
   "format": "ms",
   "valueName": "max",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http_req_duration",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/^$URL$/" },
      { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$Group$/" },
      { "condition": "AND", "key": "scenario", "operator": "=~", "value": "/^$Scenarios$/" },
      { "condition": "AND", "key": "env", "operator": "=~", "value": "/^$Environment$/" }
     ]
    }
   ]
  },
  {
   "title": "API Calls",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 0 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http_req_duration",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/^$URL$/" },
      { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$Group$/" },
      { "condition": "AND", "key": "scenario", "operator": "=~", "value": "/^$Scenarios$/" },
      { "condition": "AND", "key": "env", "operator": "=~", "value": "/^$Environment$/" }
     ]
    }
   ]
  },
  {
   "title": "Response Times (with users)",
   "type": "graph",
   "description": "Grouped by 1 sec intervals",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "p95",
     "groupBy": [
      { "params": [ "5s" ], "type": "time" }
     ],
     "measurement": "http_req_duration",
     "query": "SELECT percentile(\"value\", 95) FROM \"http_req_duration\" WHERE (\"name\" =~ /^$URL$/ AND \"group\" = 'select tag value') AND $timeFilter GROUP BY time(10s)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [
         95
        ],
        "type": "percentile"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/^$URL$/" },
      { "condition": "AND", "key": "AND", "operator": "=~", "value": "/^$Group$/" },
      { "condition": "AND", "key": "scenario", "operator": "=~", "value": "/^$Scenarios$/" },
      { "condition": "AND", "key": "env", "operator": "=~", "value": "/^$Environment$/" }
     ]
    },
    {
     "alias": "p90",
     "groupBy": [
      { "params": [ "5s" ], "type": "time" }
     ],
     "measurement": "http_req_duration",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "90" ], "type": "percentile" }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/^$URL$/" },
      { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$Group$/" },
      { "condition": "AND", "key": "scenario", "operator": "=~", "value": "/^$Scenarios$/" },
      { "condition": "AND", "key": "env", "operator": "=~", "value": "/^$Environment$/" }
     ]
    },
    {
     "alias": "min",
     "groupBy": [
      { "params": [ "5s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http_req_duration",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/^$URL$/" },
      { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$Group$/" },
      { "condition": "AND", "key": "scenario", "operator": "=~", "value": "/^$Scenarios$/" },
      { "condition": "AND", "key": "env", "operator": "=~", "value": "/^$Environment$/" }
     ]
    },
    {
     "alias": "users",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "vus",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$Environment$/" }
     ]
    }
   ]
  },
  {
   "title": "Response Times (with errors)",
   "type": "graph",
   "description": "Grouped by 1 sec intervals",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "p95",
     "groupBy": [
      { "params": [ "5s" ], "type": "time" }
     ],
     "measurement": "http_req_duration",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [
         95
        ],
        "type": "percentile"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/^$URL$/" },
      { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$Group$/" },
      { "condition": "AND", "key": "scenario", "operator": "=~", "value": "/^$Scenarios$/" },
      { "condition": "AND", "key": "env", "operator": "=~", "value": "/^$Environment$/" }
     ]
    },
    {
     "alias": "p90",
     "groupBy": [
      { "params": [ "5s" ], "type": "time" }
     ],
     "measurement": "http_req_duration",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "90" ], "type": "percentile" }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/^$URL$/" },
      { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$Group$/" },
      { "condition": "AND", "key": "scenario", "operator": "=~", "value": "/^$Scenarios$/" },
      { "condition": "AND", "key": "env", "operator": "=~", "value": "/^$Environment$/" }
     ]
    },
    {
     "alias": "min",
     "groupBy": [
      { "params": [ "5s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http_req_duration",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/^$URL$/" },
      { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$Group$/" },
      { "condition": "AND", "key": "scenario", "operator": "=~", "value": "/^$Scenarios$/" },
      { "condition": "AND", "key": "env", "operator": "=~", "value": "/^$Environment$/" }
     ]
    },
    {
     "alias": "errors",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" }
     ],
     "measurement": "rio_errors",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/^$URL$/" },
      { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$Group$/" },
      { "condition": "AND", "key": "scenario", "operator": "=~", "value": "/^$Scenarios$/" },
      { "condition": "AND", "key": "env", "operator": "=~", "value": "/^$Environment$/" }
     ]
    }
   ]
  },
  {
   "title": "Requests per Second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Requests per Second",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http_reqs",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/^$URL$/" },
      { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$Group$/" },
      { "condition": "AND", "key": "scenario", "operator": "=~", "value": "/^$Scenarios$/" },
      { "condition": "AND", "key": "env", "operator": "=~", "value": "/^$Environment$/" }
     ]
    }
   ]
  },
  {
   "title": "Response Heat Map",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 10 },
   "targets": [
    {
     "measurement": "http_req_duration",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/^$URL$/" },
      { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$Group$/" },
      { "condition": "AND", "key": "scenario", "operator": "=~", "value": "/^$Scenarios$/" },
      { "condition": "AND", "key": "env", "operator": "=~", "value": "/^$Environment$/" }
     ]
    }
   ]
  },
  {
   "title": "Errors Per Second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "errors",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" }
     ],
     "measurement": "rio_errors",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "errorCode", "operator": "<>", "value": "200" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$URL$/" },
      { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$Group$/" },
      { "condition": "AND", "key": "scenario", "operator": "=~", "value": "/^$Scenarios$/" },
      { "condition": "AND", "key": "env", "operator": "=~", "value": "/^$Environment$/" }
     ]
    },
    {
     "alias": "users",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "vus",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$Environment$/" }
     ]
    }
   ]
  },
  {
   "title": "Checks Per Second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 10 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$tag_check",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "check" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "checks",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/^$URL$/" },
      { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$Group$/" },
      { "condition": "AND", "key": "scenario", "operator": "=~", "value": "/^$Scenarios$/" },
      { "condition": "AND", "key": "env", "operator": "=~", "value": "/^$Environment$/" }
     ]
    }
   ]
  },
  {
   "title": "Endpoints",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Endpoint Latency",
     "type": "table-old",
     "gridPos": { "h": 37, "w": 24, "x": 0, "y": 18 },
     "targets": [
      {
       "alias": "min",
       "groupBy": [
        { "params": [ "name" ], "type": "tag" }
       ],
       "measurement": "http_req_duration",
       "query": "SELECT count(\"value\"), min(\"value\"), median(\"value\"), max(\"value\"), mean(\"value\"), percentile(\"value\", 95) FROM /^$Measurement$/ WHERE (\"scenario\" =~ /^$Scenarios$/ AND \"group\" =~ /^$Group$/ AND \"name\" =~ /^$URL$/) AND $timeFilter GROUP BY \"group\", \"name\"",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "count"
         }
        ],
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "min"
         }
        ],
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "median"
         }
        ],
        [
         { "params": [ "value" ], "type": "field" },
         { "params": [ "90" ], "type": "percentile" }
        ],
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [
           95
          ],
          "type": "percentile"
         }
        ],
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ],
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "scenario", "operator": "=~", "value": "/^$Scenarios$/" },
        { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$Group$/" },
        { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$URL$/" },
        { "condition": "AND", "key": "env", "operator": "=~", "value": "/^$Environment$/" }
       ]
      }
     ]
    }
   ]
  }
 ]
}